### ISSUE TITLE
Gulp process does not end when testing an app

### ISSUE THREAD

**Issue by ColemanGariety** [sindresorhus/gulp-mocha#1]
After a success or failure, if there's still part of the node process running, the gulp process never ends, and to return to the command line, you must `CTRL+C` out of Gulp.

Shouldn't gulp kill anything it requires, such as an app for testing?

**Comment by sloppylopez** [comment]
nicholaswyoung solution works

**Comment by ghostsquad** [comment]
I think @meoguru's solution is better. The problem with @nicholaswyoung's solution is when you have tasks that chain. gulp-exit is seemingly equivalent to @nicholaswyoung's solution, and doesn't work with chained tasks.

**Comment by gisterpages** [comment]
Actually I read the gulp document and I think the following understanding was missing.
Gulp runs and does not end because you have a "watch" task in it, watch will keep the gulp running and updates your design each time you make a design change.
Gulp starting and not stopping is obvious and I believe its not an error.

Try removing your watch and you can see the gulp closes.

MORE:
Gulp processes all your design at design time with watch, Else you might have to run gulp each time before testing your design in your browser.

Hope you find my answer useful.
Thanks.

**Comment by ghostsquad** [comment]
@gisterpages if the "watch" task is not included in the command, this problem still exists.

**Comment by justinr1234** [comment]
Fixed for me: https://github.com/dreame4/gulp-exit

**Comment by briankueck** [comment]
@ngthanhtrung Yippie! That fixed my issue with Gulp & having Watchify being stuck like that. Thank you!

**Comment by heldrida** [comment]
@ngthanhtrung your solution seems to work! doesn't break chained tasks, need further testing though, but so far all good! Thanks!
