### ISSUE TITLE
gulp-mocha dies silently when running too many test files

### ISSUE THREAD

**Issue by mcharytoniuk** [sindresorhus/gulp-mocha#52]
[gulp-mocha](https://github.com/sindresorhus/gulp-mocha) uses [through2](https://github.com/rvagg/through2) package internally which has `highWaterMark` option set by default to 16:
https://github.com/rvagg/through2/blob/ee2720526f58d5f58e0af5179ca170dbfdf34fbf/through2.js#L88

I have 36 test files in my project and due to this option tests just do not run and `gulp` dies without any error message (it allows me to pass only 16 test files to [gulp-mocha](https://github.com/sindresorhus/gulp-mocha); when I try to pass more via gulp pipe it just exits with exit code 0). 

Can you please expose `through2` options so I can increase its `highWaterMark` limit manually in my project's gulpfile or can you fix this issue in any other way so running multiple test files is possible?

**Comment by hershmire** [comment]
I'm seeing this issue with the latest gulp-mocha. However, it silently fails (never runs any of the tests and just completes) when there are 80 or more test files it's trying to deal with. It has something to do with `through` and adding the files to the queue – `this.queue(file)`. I've added a counter in gulp-mocha/index.js to see if I can get tests to run by limiting the amount of test files to add. See below:

**This will pass because I limit it to 79 total tests:**
```js
var counter = 0;
return through(function(file) {
	mocha.addFile(file.path);
	// this.queue(file);
	counter++;
	if (counter < 80) {
		console.log('File:', counter, file.path);
		this.queue(file);
	}
}, function() {
	var self = this;
	var d = domain.create();
	var runner;
...
```

**This will silently fail because it uses 80 tests:**
```js
var counter = 0;
return through(function(file) {
	mocha.addFile(file.path);
	// this.queue(file);
	counter++;
	if (counter <= 80) {
		console.log('File:', counter, file.path);
		this.queue(file);
	}
}, function() {
	var self = this;
	var d = domain.create();
	var runner;
...
```

**Comment by shellscape** [comment]
@hershmire would encourage you to mention that issue with the through project if that's truly the culprit (or to triage whether it is).

**Comment by hershmire** [comment]
I looked into this further. What's the reason for `this.queue(file)`? I removed it completely and all tests ran.

**Comment by shellscape** [comment]
https://github.com/dominictarr/through/blob/master/index.js#L40 is the source for that method. I'm not familiar with the `through` module, though. this will be moot as #151 uses `through2`
